// Integration check: run with BD and the built shared creator on PATH.
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdtempSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { createBead, resolveCreator } from "../lib/beads-create.mjs";

const original = process.env.BEADS_CREATE_BIN;
const creator = await resolveCreator();
const workspace = mkdtempSync(path.join(os.tmpdir(), "beads-creator-test-"));
const env = Object.fromEntries(Object.entries(process.env).filter(([key]) => !/^(BD_|BEADS_|GIT_)/.test(key)));
env.BD_METRICS_DISABLED = "true";
env.DO_NOT_TRACK = "1";
const run = (bin, args) => execFileSync(bin, args, { cwd: workspace, env, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
run("git", ["init", "-q"]);
run("git", ["config", "user.name", "Synthetic test"]);
run("git", ["config", "user.email", "test@example.invalid"]);
run("bd", ["init", "--prefix", "sample", "--non-interactive", "--skip-agents", "--skip-hooks"]);
const protocol = JSON.parse(run(creator, ["protocol"]));
assert.equal(protocol.scheme, "typed-sequential-v1");
const cli = (...args) => JSON.parse(run(creator, ["create", "--workspace", workspace, "--actor", "test-cli", ...args]));
const projectOp = randomUUID();
const project = cli("--type", "epic", "--title", "Synthetic project", "--operation", projectOp);
assert.equal(project.id, "proj-1");
assert.equal(project.status, "open");
assert.equal(cli("--type", "epic", "--title", "Synthetic project", "--operation", projectOp).id, "proj-1");
const milestone = cli("--type", "milestone", "--title", "Synthetic milestone", "--parent", project.id);
assert.equal(milestone.id, "milestone-1");
process.env.BEADS_CREATE_BIN = creator;
const input = { title: "Literal $(text) `value`", description: "Synthetic", issue_type: "bug", priority: 1, parent: milestone.id, assignee: "test-owner", labels: ["sample"], status: "idea", operation: randomUUID() };
const ticket = await createBead(workspace, "bd", "test-web", input);
assert.equal(ticket.id, "id-1");
assert.equal(ticket.status, "idea");
assert.equal(ticket.assignee, "test-owner");
assert.equal((await createBead(workspace, "bd", "test-web", input)).id, ticket.id);
await assert.rejects(createBead(workspace, "bd", "test-web", { ...input, priority: 3 }));
const next = cli("--title", "Another ticket", "--parent", project.id);
assert.equal(next.id, "id-2");
const ready = await createBead(workspace, "bd", "test-web", { ...input, title: "Ready ticket", status: "open", operation: randomUUID() });
assert.equal(ready.id, "id-3");
assert.equal(ready.status, "open");
// Exact CLI readback, independent of the helper's returned record.
const raw = JSON.parse(run("bd", ["--sandbox", "--readonly", "--json", "show", ready.id]));
const rows = raw.data || raw;
assert.equal(rows[0].id, "id-3");
assert.equal(rows[0].title, "Ready ticket");
// A configured outdated creator must fail rather than silently use another binary.
const incompatible = path.join(workspace, "old-creator");
writeFileSync(incompatible, '#!/bin/sh\nprintf \'{"protocol":"beads-create","version":0,"scheme":"legacy"}\\n\'\n', { mode: 0o700 });
process.env.BEADS_CREATE_BIN = incompatible;
await assert.rejects(resolveCreator(), /Sequential creator unavailable/);
process.env.BEADS_CREATE_BIN = path.join(workspace, "missing-creator");
await assert.rejects(createBead(workspace, "bd", "test-web", { ...input, operation: randomUUID() }), /Sequential creator unavailable/);
const all = JSON.parse(run("bd", ["--sandbox", "--readonly", "--json", "list", "--all", "--limit", "0"]));
assert.equal((all.data || all).length, 5);
if (original === undefined) delete process.env.BEADS_CREATE_BIN; else process.env.BEADS_CREATE_BIN = original;
console.log("PASS shared CLI/web sequences, fields, retry tokens, exact readback and incompatible-helper refusal");
console.log(`Synthetic workspace: ${workspace}`);
